export const DATA_LIST_REQUEST = "DATA_LIST_REQUEST";
export const DATA_LIST_SUCCESS = "DATA_LIST_SUCCESS";
export const DATA_LIST_FAILURE = "DATA_LIST_FAILURE";

export const DATA_DETAILS_REQUEST = "DATA_DETAILS_REQUEST";
export const DATA_DETAILS_SUCCESS = "DATA_DETAILS_SUCCESS";
export const DATA_DETAILS_FAILURE = "DATA_DETAILS_FAILURE";